[tools]

"ubi:evilmartians/lefthook" = "latest"
"ubi:mazznoer/lolcrab" = "latest"
"ubi:tamasfe/taplo" = "latest"
bun = "latest"
"ubi:crate-ci/committed" = "latest"
dprint = "latest"
gitleaks = "latest"
lua-language-server = "2"
node = "22"
"npm:@logseq/cli" = "latest"
ripgrep = "latest"
shellcheck = "0.10"
stylua = "2"
task = "latest"
typos = "latest"
yamllint = "1.35"
shfmt = "latest"
lua = "5.1"

[settings]
experimental = true
